baseURL      = "https://example.com/"
languageCode = "en-us"
title        = "My Hugo Site"

disableKinds = ["taxonomy", "term", "section"]

[versions]
    [versions.v1]

[module]
    [[module.imports]]
        disable       = false
        ignoreConfig  = false
        ignoreImports = false
        path          = 'github.com/bep/hugo-testing-git-versions'
        version       = 'bf9db097d1b46a118c691f5d1dcd03a8cfbdb7d9'
        [[module.imports.mounts]]
            source = 'content'
            target = 'content'
            [module.imports.mounts.sites.matrix]
                versions = '>= v1'
